<a href="https://colab.research.google.com/github/vandanasri/MLProjectRepo/blob/main/p04-Vandana/audits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [23]:
# import New York City Airbnb Open Dataset
df = pd.read_csv("/content/AB_NYC_2019.csv", skipinitialspace=True)

In [24]:
df.shape

(48895, 16)

Adult dataset has 16 rows and 48895 columns

In [31]:
# Column names
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='object')

In [33]:
# There is no duplicate columns
df.columns.has_duplicates

False

In [34]:
df.head(10)

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0
5,5099,Large Cozy 1 BR Apartment In Midtown East,7322,Chris,Manhattan,Murray Hill,40.74767,-73.97500,Entire home/apt,200,3,74,2019-06-22,0.59,1,129
6,5121,BlissArtsSpace!,7356,Garon,Brooklyn,Bedford-Stuyvesant,40.68688,-73.95596,Private room,60,45,49,2017-10-05,0.40,1,0
7,5178,Large Furnished Room Near B'way,8967,Shunichi,Manhattan,Hell's Kitchen,40.76489,-73.98493,Private room,79,2,430,2019-06-24,3.47,1,220
8,5203,Cozy Clean Guest Room - Family Apt,7490,MaryEllen,Manhattan,Upper West Side,40.80178,-73.96723,Private room,79,2,118,2017-07-21,0.99,1,0
9,5238,Cute & Cozy Lower East Side 1 bdrm,7549,Ben,Manhattan,Chinatown,40.71344,-73.99037,Entire home/apt,150,1,160,2019-06-09,1.33,4,188


In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   id                              48895 non-null  int64  
 1   name                            48879 non-null  object 
 2   host_id                         48895 non-null  int64  
 3   host_name                       48874 non-null  object 
 4   neighbourhood_group             48895 non-null  object 
 5   neighbourhood                   48895 non-null  object 
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  object 
 9   price                           48895 non-null  int64  
 10  minimum_nights                  48895 non-null  int64  
 11  number_of_reviews               48895 non-null  int64  
 12  last_review                     

There are 10 numerical features and 6 categorical features


In [35]:
# Checking for null values in dataset
df.isna().sum()

,0
id,0
name,16
host_id,0
host_name,21
neighbourhood_group,0
neighbourhood,0
latitude,0
longitude,0
room_type,0
price,0


'Name' has 16 missing values.

'host_name' has 21 missing values.

'last_review' has 10052 missing values

'reviews_per_month' has 10052 missing values.

In [30]:
(df=="?").sum()

,0
id,0
name,0
host_id,0
host_name,0
neighbourhood_group,0
neighbourhood,0
latitude,0
longitude,0
room_type,0
price,0


R-1 Below is the table, which show all four required properties of Airbnb dataset.

In [38]:
air_bnb_prop_table = pd.DataFrame(
    {
        "data_type": df.dtypes,
        "missing_count":df.isna().sum(),
        "missing_percentage":(df.isna().mean()*100).round(2),
        "unique_count":df.nunique()
    }
)

air_bnb_prop_table

,data_type,missing_count,missing_percentage,unique_count
id,int64,0,0.00,48895
name,object,16,0.03,47905
host_id,int64,0,0.00,37457
host_name,object,21,0.04,11452
neighbourhood_group,object,0,0.00,5
neighbourhood,object,0,0.00,221
latitude,float64,0,0.00,19048
longitude,float64,0,0.00,14718
room_type,object,0,0.00,3
price,int64,0,0.00,674


## R-2 Audit

### get maximun and min for numeric columns and categorical, get Numerical and categorical columns seperatly.

In [40]:
#numerical columns
numerical_cols = df.select_dtypes(include=np.number).columns
# Categorical columns
categorical_cols = df.select_dtypes(exclude=np.number).columns
print("Numerical columns:", numerical_cols)
print("Categorical columns:", categorical_cols)

Numerical columns: Index(['id', 'host_id', 'latitude', 'longitude', 'price', 'minimum_nights',
       'number_of_reviews', 'reviews_per_month',
       'calculated_host_listings_count', 'availability_365'],
      dtype='object')
Categorical columns: Index(['name', 'host_name', 'neighbourhood_group', 'neighbourhood',
       'room_type', 'last_review'],
      dtype='object')


In [42]:
# min columns
df[numerical_cols].min()

,0
id,2539.00000
host_id,2438.00000
latitude,40.49979
longitude,-74.24442
price,0.00000
minimum_nights,1.00000
number_of_reviews,0.00000
reviews_per_month,0.01000
calculated_host_listings_count,1.00000
availability_365,0.00000


In [101]:
# Print only the top 3 category names for each categorical column
def get_top_3_categories_list(cat_columns:list):
  top_3_categories_list = []
  for col in cat_columns:
    top_3_categories = df[col].value_counts().head(3)
    top_3_categories_list.append(top_3_categories)
  return top_3_categories_list

In [103]:
#list top top 3 values of categorical columns
display(get_top_3_categories_list(categorical_cols))

[name
 Hillside Hotel                  18
 Home away from home             17
 New york Multi-unit building    16
 Name: count, dtype: int64,
 host_name
 Michael         417
 David           403
 Sonder (NYC)    327
 Name: count, dtype: int64,
 neighbourhood_group
 Manhattan    21661
 Brooklyn     20104
 Queens        5666
 Name: count, dtype: int64,
 neighbourhood
 Williamsburg          3920
 Bedford-Stuyvesant    3714
 Harlem                2658
 Name: count, dtype: int64,
 room_type
 Entire home/apt    25409
 Private room       22326
 Shared room         1160
 Name: count, dtype: int64,
 last_review
 2019-06-23    1413
 2019-07-01    1359
 2019-06-30    1341
 Name: count, dtype: int64]

In [104]:
# Calculate top 3 categories mapping for categorical columns
top3_map = {}
for col in df.columns:
    if col in categorical_cols:
        top3_map[col] = df[col].value_counts().head(3).index.tolist()
    else:
        top3_map[col] = np.nan

# Created audit table
air_bnb_prop_table = pd.DataFrame(
    {
        "dtype": df.dtypes,
        "%missing": (df.isna().mean() * 100).round(2),
        "distinct": df.nunique(dropna=True),
        "min": df[numerical_cols].min().round(2),
        "max": df[numerical_cols].max().round(2),
        "top3_categories": pd.Series(top3_map)
    }
)

# Reset the index as "columns"
air_bnb_prop_table.index.name = "columns"
air_bnb_prop_table = air_bnb_prop_table.reset_index()
air_bnb_prop_table

,columns,dtype,%missing,distinct,min,max,top3_categories
0,availability_365,int64,0.00,366,0.00,365.00,NaN
1,calculated_host_listings_count,int64,0.00,47,1.00,327.00,NaN
2,host_id,int64,0.00,37457,2438.00,274321313.00,NaN
3,host_name,object,0.04,11452,NaN,NaN,"[Michael, David, Sonder (NYC)]"
4,id,int64,0.00,48895,2539.00,36487245.00,NaN
5,last_review,object,20.56,1764,NaN,NaN,"[2019-06-23, 2019-07-01, 2019-06-30]"
6,latitude,float64,0.00,19048,40.50,40.91,NaN
7,longitude,float64,0.00,14718,-74.24,-73.71,NaN
8,minimum_nights,int64,0.00,109,1.00,1250.00,NaN
9,name,object,0.03,47905,NaN,NaN,"[Hillside Hotel, Home away from home, New york..."
